

-- 1. Display the structure of the MM_MEMBER table.
select * from MM_MEMBER;

-- 2. Add yourself as a member.
INSERT INTO MM_MEMBER (MEMBER_ID, LAST, FIRST) VALUES (15, 'Choi', 'Hyun');

-- 3. Modify your membership by adding a made-up credit card number.
UPDATE MM_MEMBER SET CREDIT_CARD='666666666666' WHERE MEMBER_ID=15;

-- 4. Remove your membership.
DELETE MM_MEMBER WHERE MEMBER_ID=15;


-- 6. Using join ... on
SELECT MM_RENTAL.RENTAL_ID, MM_MEMBER.LAST, MM_MOVIE.MOVIE_TITLE FROM MM_RENTAL
LEFT JOIN MM_MEMBER ON MM_RENTAL.MEMBER_ID = MM_MEMBER.MEMBER_ID
LEFT JOIN MM_MOVIE ON MM_RENTAL.MOVIE_ID = MM_MOVIE.MOVIE_ID
ORDER BY MM_RENTAL.RENTAL_ID;

-- 7. Using traditional join
SELECT MM_RENTAL.RENTAL_ID, MM_MEMBER.LAST, MM_MOVIE.MOVIE_TITLE
FROM MM_RENTAL, MM_MEMBER, MM_MOVIE
WHERE MM_RENTAL.MEMBER_ID = MM_MEMBER.MEMBER_ID(+)
AND MM_RENTAL.MOVIE_ID = MM_MOVIE.MOVIE_ID(+)
ORDER BY MM_RENTAL.RENTAL_ID;

-- 8. Creating a new table
CREATE TABLE MY_TABLE (
    MY_NUMBER NUMBER,
    MY_DATE DATE,
    MY_STRING VARCHAR2(5)
);

-- 9. Creating a new sequence
CREATE SEQUENCE SEQ_MOVIE_ID
START WITH 20
INCREMENT BY 2;

-- 10. Displaying sequence information
SELECT SEQUENCE_NAME, LAST_NUMBER, INCREMENT_BY
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = 'SEQ_MOVIE_ID';

-- 11. Show next sequence number
SELECT SEQ_MOVIE_ID.NEXTVAL
FROM dual;

-- 12. Change the sequence created in Step 9 to increment by 5 instead of 2.
ALTER SEQUENCE SEQ_MOVIE_ID
INCREMENT BY 5;

-- 13. Add your favorite movie to the MM_MOVIE table using the sequence from the previous step
-- for the movie_id.
INSERT INTO MM_MOVIE(MOVIE_ID, MOVIE_TITLE, MOVIE_CAT_ID, MOVIE_VALUE, MOVIE_QTY) VALUES (SEQ_MOVIE_ID.nextval, 'Don''t Look up', 1, 10.00, 44);


-- 14. Creating a view
CREATE VIEW VW_MOVIE_RENTAL AS
SELECT MM_RENTAL.RENTAL_ID, MM_MEMBER.LAST, MM_MOVIE.MOVIE_TITLE
FROM MM_RENTAL
LEFT JOIN MM_MEMBER ON MM_RENTAL.MEMBER_ID = MM_MEMBER.MEMBER_ID
LEFT JOIN MM_MOVIE ON MM_RENTAL.MOVIE_ID = MM_MOVIE.MOVIE_ID
ORDER BY MM_RENTAL.RENTAL_ID;

-- 15. Use a query to display the data accessed by the VW_MOVIE_RENTAL view.
SELECT * FROM VW_MOVIE_RENTAL;


