
rem Lab Unit 12 Using joins
set echo on
set linesize 133
set pagesize 66
spool C:/dev/sait/db/joinLabOutput.txt

rem Q1

COLUMN FIRST_NAME FORMAT A12;
COLUMN LAST_NAME FORMAT A12;
COLUMN TOUR_DESCRIPTION FORMAT A22;
COLUMN ORDER# FORMAT 910;
COLUMN DEST_DESCRIPTION FORMAT A70;

BREAK ON "FIRST NAME" ON TOUR_DESCRIPTION;

SELECT c.FIRST_NAME "FIRST NAME", LAST_NAME, TOUR_DESCRIPTION, ORDER#, DEST_DESCRIPTION
FROM RCV_CUSTOMER C
JOIN RCV_TOUR_CUSTOMER USING(CUSTOMER_NUMBER)
JOIN RCV_VACATION_TOUR USING(TOUR_CODE)
JOIN RCV_TOUR_DESTINATION USING(TOUR_CODE)
JOIN RCV_DESTINATION USING(DEST_CODE)
WHERE FIRST_NAME='Sheldon' AND LAST_NAME='Cooper'
ORDER BY 3, 4;

clear breaks

rem Q2

SELECT FIRST_NAME, LAST_NAME, TOUR_DESCRIPTION, ORDER#, DEST_DESCRIPTION
FROM RCV_CUSTOMER
         JOIN RCV_TOUR_CUSTOMER ON RCV_CUSTOMER.CUSTOMER_NUMBER = RCV_TOUR_CUSTOMER.CUSTOMER_NUMBER
         JOIN RCV_VACATION_TOUR ON RCV_TOUR_CUSTOMER.TOUR_CODE = RCV_VACATION_TOUR.TOUR_CODE
         JOIN RCV_TOUR_DESTINATION ON RCV_VACATION_TOUR.TOUR_CODE = RCV_TOUR_DESTINATION.TOUR_CODE
         JOIN RCV_DESTINATION ON RCV_TOUR_DESTINATION.DEST_CODE = RCV_DESTINATION.DEST_CODE
WHERE FIRST_NAME='Sheldon' AND LAST_NAME='Cooper'
ORDER BY 3, 4;

CLEAR COLUMNS
CLEAR BREAKS

rem Q3

COLUMN DEST_DESCRIPTION FORMAT A86;
COLUMN FIRST_NAME FORMAT A20;
COLUMN LAST_NAME FORMAT A22;

SELECT DISTINCT DEST_DESCRIPTION, FIRST_NAME, LAST_NAME
FROM RCV_DESTINATION
         LEFT JOIN RCV_TOUR_DESTINATION ON RCV_DESTINATION.DEST_CODE = RCV_TOUR_DESTINATION.DEST_CODE
         LEFT JOIN RCV_VACATION_TOUR ON RCV_TOUR_DESTINATION.TOUR_CODE = RCV_VACATION_TOUR.TOUR_CODE
         LEFT JOIN RCV_TOUR_CUSTOMER ON RCV_VACATION_TOUR.TOUR_CODE = RCV_TOUR_CUSTOMER.TOUR_CODE
         LEFT JOIN RCV_CUSTOMER ON RCV_TOUR_CUSTOMER.CUSTOMER_NUMBER = RCV_CUSTOMER.CUSTOMER_NUMBER
WHERE COUNTRY='Canada'
ORDER BY DEST_DESCRIPTION, LAST_NAME;

CLEAR COLUMNS
CLEAR BREAKS

rem Q4


COLUMN FIRST_NAME FORMAT A15;
COLUMN LAST_NAME FORMAT A20;

BREAK ON FIRST_NAME ON LAST_NAME;

SELECT FIRST_NAME, LAST_NAME, TRAINING_DESCRIPTION,
       DATE_COMPLETED AS "Date Comp"
FROM RCV_AGENT
NATURAL JOIN RCV_AGENT_TRAINING
NATURAL JOIN RCV_TRAINING
ORDER BY 1, 2, 3;

CLEAR COLUMNS
CLEAR BREAKS

SPOOL OFF
